add cx 3

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,6 +34,33 @@ jobs:
           name: codestyle-logs
           path: PPO_f/build/codestyle-results/output.log
 
+  check-quality-gate:
+    runs-on: ubuntu-latest
+    outputs:
+      passed: ${{ steps.check.outputs.passed }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Run QualityGate checks
+        id: check
+        run: |
+          cd PPO_f
+          chmod +x gradlew
+          mkdir -p build/checkQualityGate-results
+          touch build/checkQualityGate-results/output.log
+
+          ./gradlew clean checkQualityGate >> build/checkQualityGate-results/output.log 2>&1 || {
+            echo "Code style checks failed" >> build/checkQualityGate-results/output.log
+            exit 1
+          }
+
+      - name: Upload CodeStyle logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: checkQualityGate-logs
+          path: PPO_f/build/checkQualityGate-results/output.log
+
 
 #
 #  unit-tests:
