test commit 3

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,8 +5,35 @@ on:
     branches: [ main, lab2 ]
 
 jobs:
+  codestyle:
+    runs-on: ubuntu-latest
+    outputs:
+      passed: ${{ steps.check.outputs.passed }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Run CodeStyle checks
+        id: check
+        run: |
+          cd PPO_f
+          chmod +x gradlew
+          mkdir -p build/codestyle-results
+          ./gradlew clean checkstyleAll\
+            > build/codestyle-results/output.log 2>&1 || {
+              echo "Code style checks failed. See build/codestyle-results/output.log"
+              exit 1
+            }
+
+      - name: Upload CodeStyle logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: codestyle-logs
+          path: ''
+
   unit-tests:
     runs-on: ubuntu-latest
+    needs: codestyle
     steps:
       - uses: actions/checkout@v4
 
@@ -33,7 +60,7 @@ jobs:
 
   integration-tests:
     runs-on: ubuntu-latest
-    needs: unit-tests
+    needs: [codestyle, unit-tests]
     if: ${{ success() }}
     steps:
       - uses: actions/checkout@v4
@@ -72,7 +99,7 @@ jobs:
 
   e2e-tests:
     runs-on: ubuntu-latest
-    needs: [unit-tests, integration-tests]
+    needs: [codestyle, unit-tests, integration-tests]
     if: ${{ success() }}
     services:
       postgres:
@@ -147,7 +174,7 @@ jobs:
 
   generate-allure-report:
     runs-on: ubuntu-latest
-    needs: [unit-tests, integration-tests, e2e-tests]
+    needs: [codestyle, unit-tests, integration-tests, e2e-tests]
     if: ${{ always() }}
     steps:
       - uses: actions/checkout@v4
